# Generated by Django 5.2.1 on 2025-06-01 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='Организация')),
                ('date', models.DateField(verbose_name='Дата получения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
                'ordering': ['-date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('issuer', models.CharField(max_length=200, verbose_name='Организация')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата истечения')),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='ID сертификата')),
                ('credential_url', models.URLField(blank=True, verbose_name='Ссылка на сертификат')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-issue_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('PHONE', 'Телефон'), ('EMAIL', 'Email'), ('TELEGRAM', 'Telegram'), ('LINKEDIN', 'LinkedIn'), ('GITHUB', 'GitHub'), ('WEBSITE', 'Веб-сайт')], max_length=20, verbose_name='Тип контакта')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Подпись')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимый')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200, verbose_name='Учебное заведение')),
                ('faculty', models.CharField(blank=True, max_length=200, verbose_name='Факультет')),
                ('degree', models.CharField(blank=True, choices=[('SECONDARY', 'Среднее'), ('SPECIALIZED_SECONDARY', 'Среднее специальное'), ('INCOMPLETE_HIGHER', 'Неоконченное высшее'), ('BACHELOR', 'Бакалавр'), ('MASTER', 'Магистр'), ('PHD', 'Кандидат наук'), ('DOCTOR', 'Доктор наук')], max_length=30, verbose_name='Степень')),
                ('field_of_study', models.CharField(blank=True, max_length=200, verbose_name='Специальность')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_current', models.BooleanField(default=False, verbose_name='Учусь сейчас')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Язык')),
                ('level', models.CharField(choices=[('A1', 'A1 - Начальный'), ('A2', 'A2 - Элементарный'), ('B1', 'B1 - Средний'), ('B2', 'B2 - Выше среднего'), ('C1', 'C1 - Продвинутый'), ('C2', 'C2 - Носитель')], max_length=2, verbose_name='Уровень')),
                ('is_native', models.BooleanField(default=False, verbose_name='Родной')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'ordering': ['-is_native', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommender_name', models.CharField(max_length=200, verbose_name='ФИО рекомендателя')),
                ('recommender_position', models.CharField(max_length=200, verbose_name='Должность рекомендателя')),
                ('recommender_company', models.CharField(blank=True, max_length=200, verbose_name='Компания рекомендателя')),
                ('recommender_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон рекомендателя')),
                ('recommender_email', models.EmailField(blank=True, max_length=254, verbose_name='Email рекомендателя')),
                ('relationship', models.CharField(blank=True, max_length=200, verbose_name='Отношение к соискателю')),
                ('text', models.TextField(blank=True, verbose_name='Текст рекомендации')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать в резюме')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, upload_to='resumes/photos/', verbose_name='Фото')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('employment_type', models.CharField(blank=True, choices=[('FULL', 'Полная занятость'), ('PART', 'Частичная занятость'), ('REMOTE', 'Удаленная работа'), ('HYBRID', 'Гибридная работа')], max_length=20, verbose_name='Тип занятости')),
                ('salary_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('currency', models.CharField(choices=[('RUB', 'Рубли'), ('USD', 'Доллары'), ('EUR', 'Евро')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичное')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('preview_image', models.ImageField(blank=True, upload_to='templates/previews/', verbose_name='Превью')),
                ('css_styles', models.JSONField(blank=True, default=dict, verbose_name='CSS стили')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Шаблон резюме',
                'verbose_name_plural': 'Шаблоны резюме',
            },
        ),
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='Уникальный идентификатор')),
                ('link_type', models.CharField(choices=[('PUBLIC', 'Публичная'), ('PROTECTED', 'Защищенная'), ('TEMPORARY', 'Временная')], default='PUBLIC', max_length=20, verbose_name='Тип ссылки')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='Пароль')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата истечения')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний просмотр')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Публичная ссылка',
                'verbose_name_plural': 'Публичные ссылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.CharField(choices=[('TECHNICAL', 'Технические'), ('SOFT', 'Гибкие'), ('LANGUAGE', 'Языковые'), ('OTHER', 'Другие')], default='TECHNICAL', max_length=20, verbose_name='Категория')),
                ('level', models.IntegerField(choices=[(1, 'Начальный'), (2, 'Базовый'), (3, 'Средний'), (4, 'Продвинутый'), (5, 'Эксперт')], default=3, verbose_name='Уровень')),
                ('is_key_skill', models.BooleanField(default=False, verbose_name='Ключевой навык')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['-is_key_skill', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_current', models.BooleanField(default=False, verbose_name='По настоящее время')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
                'ordering': ['-start_date', 'order'],
            },
        ),
    ]
