# Generated by Django 5.0.1 on 2025-06-01 16:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тег навыка',
                'verbose_name_plural': 'Теги навыков',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.AlterModelOptions(
            name='resumetemplate',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'Шаблон резюме', 'verbose_name_plural': 'Шаблоны резюме'},
        ),
        migrations.AlterField(
            model_name='award',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='resumes.resume', verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='resumes.resume', verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='resumes.resume', verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='resumes.resume', verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='language',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='resumes.resume', verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='resumes.resume', verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='resumes.resumetemplate', verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='resumes.resume', verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resumes.resume', verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='resumes.resume', verbose_name='Резюме'),
        ),
        migrations.CreateModel(
            name='SkillTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.IntegerField(default=100, verbose_name='Релевантность')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.skill', verbose_name='Навык')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.skilltag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Связь навык-тег',
                'verbose_name_plural': 'Связи навык-тег',
                'ordering': ['-relevance'],
                'unique_together': {('skill', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='tags',
            field=models.ManyToManyField(related_name='skills', through='resumes.SkillTagRelation', to='resumes.skilltag', verbose_name='Теги'),
        ),
    ]
