# Generated by Django 5.0.1 on 2025-06-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_skilltag_alter_resume_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, upload_to='certificates/', verbose_name='Файл сертификата'),
        ),
    ]
