# Generated by Django 5.0.1 on 2025-06-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_certificate_certificate_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='tags',
        ),
        migrations.AddField(
            model_name='skill',
            name='color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='Цвет'),
        ),
    ]
